### PR TITLE
Add support for django official versions

### PR DESCRIPTION
**Pull request by irtazaakram**
Hi

I've made this PR that

- add support for Django 4.1 & 4.2
- drop support for Django 4.0
- add support for Python 3.11
- update GitHub actions

can we also have a new release after this PR is merged?

Thanks

### CODE REVIEW

**Review by zyegfryed — CHANGES_REQUESTED** [review]
Hi @irtazaakram and thanks for your contribution, really appreciated!

AFAIK, Django 3.2 (LTS) still [supports Python 3.6 and 3.7](https://docs.djangoproject.com/en/4.2/releases/3.2/#python-compatibility). I searched the release notes for the 3.2 series but I haven't found any deprecation of those Python versions. Thus, can you bring back the support for those in your PR, please?

I noticed Django [4.1 (since 4.1.3)](https://docs.djangoproject.com/en/4.2/releases/4.1/#python-compatibility) and [4.2](https://docs.djangoproject.com/en/4.2/releases/4.2/#python-compatibility) are also compatible with Python 3.11. Would you be keen on adding support for that Python version too?

Once done, we should be good to merge and cut a release because every other changes lgtm 👍🏻

PS: I'm just about to leave for some holidays, expect some delay from my side :(

**Comment by irtazaakram** [comment]
Hi @zyegfryed,

Thank you for the review. 

I've added back python 3.6 & 3.7 and also added 3.11 to tests. 

Enjoy your holidays :-)

Thanks,

**Comment by irtazaakram** [comment]
Hey @zyegfryed,

Apologies. I used incorrect python name in `build.yml`. I've fixed it and also updated python versions.

Again sorry.

**Review by zyegfryed — APPROVED** [review]
Perfect 👌🏻

**Comment by zyegfryed** [comment]
@irtazaakram just merged your PR in the main branch, thanks for your great job.
Will try to cut a release within few days

**Comment by irtazaakram** [comment]
Thank you @zyegfryed

**Comment by zyegfryed** [comment]
Hi @irtazaakram,
I just cut the release [v2.4.0](https://pypi.org/project/django-statici18n/2.4.0/) with the [up-to-date docs](https://django-statici18n.readthedocs.io/en/latest/changelog.html#v2-4-0-2023-jul-29).
Thanks agin for your great work 👍🏻

**Comment by irtazaakram** [comment]
Thank you @zyegfryed 🙌

**Pull request merged**
