### PR TITLE
Add support for Django 1.8, 1.9 and 1.10

### LINKED ISSUE #18: Django 1.9 / 1.10
Please, add Django 1.9 and 1.10 support.
Under Django 1.9 there is warning: 
```
/django/core/management/__init__.py:345: RemovedInDjango110Warning: OptionParser usage for Django management commands is deprecated, use ArgumentParser instead
  self.fetch_command(subcommand).run_from_argv(self.argv)
```

In Django 1.10 will be error!

Or is this package dead and without support?

### PR DESCRIPTION
**Pull request by julen**
This PR adds support for Django 1.8, 1.9 and 1.10. It also drops support for Django 1.4, 1.5, 1.6 and 1.7. Support for Python 2.6 has been dropped as well, and support for Python 3.5 has been added.

@zyegfryed I have reused parts of your branch, but not the entirety of it as some changes didn't make sense now that support for older Django versions is dropped. I tried to attribute those changes to you, I hope you don't mind 😄

Fixes #18.

### CODE REVIEW

**Comment by julen** [comment]
I don't have a Py3 interpreter locally, so waiting to hear from Travis... 2.7 worked fine on my end.

**Comment by zyegfryed** [comment]
Hi @julen ,
Thanks for your work on the PR. In order to merge it, would you mind to rebase all your commits into only one?
Cheers

**Comment by julen** [comment]
Hey @zyegfryed, hope you had a good vacation time 😄

When you say rebase... I guess you mean squash?

To be honest, I don't see much point on doing so because the existing commits are logically split and helps anyone understand why the changes happened (instead of having a generic _Add Django X support, drop Y support_ in the commit log which hides the _why_). Having said that, I can do it if you strongly favor squashing and are willing to block the PR on that, although I'd prefer not to for the reasons stated above.

**Comment by zyegfryed** [comment]
Thanks! 🍰

**Comment by julen** [comment]
Wonderful, thanks for the quick action! Will we be able to see a new release anytime soon? 👼

**Comment by zyegfryed** [comment]
There's still 2 PRs (#17 and #23) on their way that I'd like to see merged before releasing a new version. Feel free to participate to them in case you have some free time to spend on ;)

**Comment by julen** [comment]
Thanks for the update; I'll keep an eye on those and participate if they don't progress quick enough — just like everyone else, I don't have much spare time!

**Pull request merged**
