### PR TITLE
Pass language name instead of locale name on Django 1.10

### PR DESCRIPTION
**Pull request by quantum5**
Even though the argument is named `locale`, it makes its way into `DjangoTranslation`, which expects it to be `language`, ultimately calls `to_locale` on it. This is not a big issue for unhyphenated languages.

However, it fails silently for languages like `zh-hans`, resulting in an empty catalog. This pull request addresses the issue, and adds a `zh-hans` test case to catch this failure.

### CODE REVIEW

**Comment by aventurella** [comment]
Definitely could use this

**Comment by dinopetrone** [comment]
yes please...

**Comment by raphaelm** [comment]
Waiting for this as well.

**Comment by raphaelm** [comment]
Yay, thanks!

**Comment by zyegfryed** [comment]
Available in [v1.3.0](https://pypi.python.org/pypi/django-statici18n/1.3.0).
Thanks @quantum5 for the great work!

**Pull request merged**
